https://towardsdatascience.com/let-us-understand-the-correlation-matrix-and-covariance-matrix-d42e6b643c22
https://blogs.sas.com/content/iml/2010/12/10/converting-between-correlation-and-covariance-matrices.html

### Transpose of a matrix

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4], [5,6]])
print("A.shape : ", A.shape)
A

A.shape :  (3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
np.mean(A, axis=0) # vertical mean, feature mean, column mean
# 2+4+6 = 12/3 = 4

array([3., 4.])

In [4]:
np.mean(A, axis=1) # horizontal mean

array([1.5, 3.5, 5.5])

In [5]:
print("A.T shape : ", A.T.shape)
A.T

A.T shape :  (2, 3)


array([[1, 3, 5],
       [2, 4, 6]])

### eigen-values of diagonal matrix, are the diagonal elements.

In [6]:
B=np.diag((1,2,3))
B

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [7]:
eigen_vals, eigen_vecs = np.linalg.eig(B)

In [8]:
eigen_vals # eigen values

array([1., 2., 3.])

In [9]:
eigen_vecs # eigen vectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
eigen_vecs[:][0]

array([1., 0., 0.])

### Q: eigen vector is horizontal or vertical?

https://docs.python.org/2/library/warnings.html

In [11]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [12]:
import pandas as pd
df = pd.read_csv(
    filepath_or_buffer='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
    header=None,
    sep=',')
df.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class']
df.dropna(how="all", inplace=True) # drops the empty line at file-end
df.tail()

sepal_len  sepal_wid  petal_len  petal_wid           class
145        6.7        3.0        5.2        2.3  Iris-virginica
146        6.3        2.5        5.0        1.9  Iris-virginica
147        6.5        3.0        5.2        2.0  Iris-virginica
148        6.2        3.4        5.4        2.3  Iris-virginica
149        5.9        3.0        5.1        1.8  Iris-virginica

In [13]:
df.shape

(150, 5)

In [14]:
X = df.ix[:,0:4].values
y = df.ix[:,4].values

<b> how ix is working? should be </b>

In [15]:
X.shape

(150, 4)

In [16]:
y.shape

(150,)

#### make the matrix standardized, mean of each feature 0, sigma=1

In [17]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X) # takes numpy array as input

In [18]:
#X_std[:4][:]
X_std[:5, ...]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [19]:
X_std.T.shape

(4, 150)

In [20]:
X_std.T[..., :5] # select all rows, first 5 columns

array([[-0.90068117, -1.14301691, -1.38535265, -1.50652052, -1.02184904],
       [ 1.03205722, -0.1249576 ,  0.33784833,  0.10644536,  1.26346019],
       [-1.3412724 , -1.3412724 , -1.39813811, -1.2844067 , -1.3412724 ],
       [-1.31297673, -1.31297673, -1.31297673, -1.31297673, -1.31297673]])

#### see how mean, std is difference between un-standardized and standardized matrix

In [21]:
print(X.mean(axis=0))
print(X.std(axis=0))

[5.84333333 3.054      3.75866667 1.19866667]
[0.82530129 0.43214658 1.75852918 0.76061262]


In [22]:
# np.mean(X) # don't do this ... this will do average of all elements of the matrix

### how standard deviation is calculated???

In [23]:
len(X[...,0]) # take the first feature

150

In [24]:
np.mean(X[...,0])

5.843333333333334

In [25]:
np.sum(X[...,0])/len(X[...,0]) # mean, is just sum of all elements divided by length

5.843333333333334

In [26]:
np.var(X[...,0])

0.6811222222222223

In [27]:
variance = np.sum((X[..., 0]-np.mean(X[...,0]))**2)/len(X[...,0]) # variance, is sum of square of the deviation divvaided by length
variance

0.6811222222222223

In [28]:
np.sqrt(variance)

0.8253012917851409

In [29]:
np.std(X[...,0])

0.8253012917851409

In [30]:
X_std.mean(axis=0)

array([-4.73695157e-16, -6.63173220e-16,  3.31586610e-16, -2.84217094e-16])

In [31]:
X_std.std(axis=0)

array([1., 1., 1., 1.])

In [32]:
np.mean(X_std[...,0])

-4.736951571734001e-16

In [33]:
np.std(X_std[...,0])

1.0

#### covariance matrix from X

In [34]:
np.cov(X.T) # the diagnoal elements are sample variance... divided by N-1

array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [35]:
X.var(axis=0) # the diagonal elements should be variance, why they are different

array([0.68112222, 0.18675067, 3.09242489, 0.57853156])

In [36]:
np.var(X, axis=0)

array([0.68112222, 0.18675067, 3.09242489, 0.57853156])

<b>
the diagonal elements should be variance, why they are different. if you will look closely they are constantly higher than  varianc calculation.
X.var .... divide by length N <br>
np.cov ... divide by N-1.. so it is higher
</b>

In [37]:
def samplevar(X):
    variance = np.sum((X-np.mean(X))**2)/(len(X)-1)
    return variance
def populationvar(X):
    variance = np.sum((X-np.mean(X))**2)/len(X)
    return variance

In [38]:
samplevar(X[...,3])

0.582414317673378

In [39]:
np.apply_along_axis(samplevar, 0, X)

array([0.68569351, 0.18800403, 3.11317942, 0.58241432])

In [40]:
# now get sample variance of all features
np.diag((X-np.mean(X, axis=0)).T.dot((X-np.mean(X, axis=0)))/(X.shape[0]-1))

array([0.68569351, 0.18800403, 3.11317942, 0.58241432])

#### covariance matrix from X_std... make sure take the transpose

In [41]:
np.cov(X_std.T) # make sure to take the transpose here
# 4 features, covariance matrix is 4x4 matrix

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

##### see diagonal elements are not exactly 1, little higher than 1.. this is sample variance, divided by N-1

In [42]:
###np.cov(X.T) # doesn't match with the above
np.apply_along_axis(populationvar, 0, X_std)

array([1., 1., 1., 1.])

In [43]:
np.apply_along_axis(samplevar, 0, X_std)

array([1.00671141, 1.00671141, 1.00671141, 1.00671141])

#### Lets calculate using formula. both of these matches. note denominator is N-1

In [44]:
mean_vec = np.mean(X_std, axis=0)
cov_mat = (X_std-mean_vec).T.dot((X_std-mean_vec))/(X_std.shape[0]-1)
cov_mat

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

In [45]:
#np.lib.twodim_base.diag(cov_mat)

In [46]:
D = np.diag(cov_mat)
D

array([1.00671141, 1.00671141, 1.00671141, 1.00671141])

In [47]:
D.shape

(4,)

In [48]:
stddev = np.sqrt(D.real)
stddev

array([1.00335009, 1.00335009, 1.00335009, 1.00335009])

In [49]:
cov_mat/D

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [50]:
# matrix1=cov_mat/stddev[:, None]
# print(matrix1)

In [51]:
# matrix2=matrix1/stddev[None, :]
# matrix2

https://github.com/numpy/numpy/blob/v1.13.0/numpy/lib/function_base.py#L3092-L3172

#### correlation matrix from X_std and X... take the transpose

In [52]:
cor_mat = np.corrcoef(X_std.T)
cor_mat

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [53]:
cor_mat1 = np.corrcoef(X.T)
cor_mat1

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [54]:
np.corrcoef(X_std).shape # don't do this... take transpose

(150, 150)

In [55]:
#### if you don't make transpose, it will become 150x150 matrix.

#### same correlation matrix from from X and X_std

#### Lets calculate using the formula... why its not matching

correlation matrix is just normalized version of covariant matrix.

In [56]:
np.cov(X.T) # diagonal elements are sample variance

array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [57]:
np.apply_along_axis(samplevar, 0, X)

array([0.68569351, 0.18800403, 3.11317942, 0.58241432])

In [58]:
np.sqrt(np.apply_along_axis(samplevar, 0, X))

array([0.82806613, 0.43359431, 1.76442042, 0.76316074])

In [59]:
#np.cov(X.T)/np.apply_along_axis(samplevar, 0, X)
np.cov(X.T)

array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [60]:
cov_mat = np.cov(X.T)
D = np.diag(cov_mat)
stddev = np.sqrt(D.real)
matrix1=cov_mat/stddev[:, None]
matrix2=matrix1/stddev[None, :]
matrix2

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [61]:
print(stddev.shape)
stddev

(4,)


array([0.82806613, 0.43359431, 1.76442042, 0.76316074])

In [62]:
print(stddev[:, None].shape)
stddev[:, None]

(4, 1)


array([[0.82806613],
       [0.43359431],
       [1.76442042],
       [0.76316074]])

In [63]:
matrix1

array([[ 0.82806613, -0.04742188,  1.53814084,  0.6242301 ],
       [-0.09056497,  0.43359431, -0.74196719, -0.27210045],
       [ 0.72187009, -0.18233339,  1.76442042,  0.73473842],
       [ 0.6773197 , -0.15459549,  1.69870828,  0.76316074]])

In [64]:
print(stddev[None, :].shape)
stddev[None, :]

(1, 4)


array([[0.82806613, 0.43359431, 1.76442042, 0.76316074]])

In [65]:
np.cov(X_std.T)

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

In [66]:
np.apply_along_axis(samplevar, 0, X_std)

array([1.00671141, 1.00671141, 1.00671141, 1.00671141])

In [67]:
np.cov(X_std.T)/np.apply_along_axis(samplevar, 0, X_std)

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [68]:
variance = np.diag(np.cov(X_std.T))
stddev = np.sqrt(variance.real)

In [69]:
stddev

array([1.00335009, 1.00335009, 1.00335009, 1.00335009])

In [70]:
deno = np.dot(stddev[None, :].T, stddev[None, :])
deno

array([[1.00671141, 1.00671141, 1.00671141, 1.00671141],
       [1.00671141, 1.00671141, 1.00671141, 1.00671141],
       [1.00671141, 1.00671141, 1.00671141, 1.00671141],
       [1.00671141, 1.00671141, 1.00671141, 1.00671141]])

In [71]:
np.cov(X_std.T)/deno

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [72]:
def covTocorrcoef(cov_mat):
    variance = np.diag(cov_mat) # take the diagonal elements
    stddev = np.sqrt(variance.real) # take square root to get sigma, 1x4 matrix
    deno = np.dot(stddev[None, :].T, stddev[None, :]) # dot product (4x1).(1x4) = 4x4
    return cov_mat/deno

In [73]:
np.corrcoef(X.T)

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [74]:
covTocorrcoef(np.cov(X.T))

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [75]:
np.corrcoef(X_std.T)

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

In [76]:
covTocorrcoef(np.cov(X_std.T))

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])

### covariance matrix is differnet from X and X_std
### correlation matrix is same from X and X_std